DROP TABLE IF EXISTS materiales;

CREATE TABLE materiales (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS tipos;

CREATE TABLE tipos (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
  cliente_id BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(250) NOT NULL,
  confirm_id BIGINT
);

DROP TABLE IF EXISTS productos;

CREATE TABLE productos (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  dire VARCHAR(250) NOT NULL,
  cost DOUBLE,
  description VARCHAR(1000) NOT NULL,
  mercado_url VARCHAR(250) NOT NULL,
  mat_id BIGINT,
  typ_id BIGINT

);

DROP TABLE IF EXISTS authorities;

CREATE TABLE authorities (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  cliente_id BIGINT AUTO_INCREMENT NOT NULL,
  name varchar(50) NOT NULL

);

DROP TABLE IF EXISTS carrito;

CREATE TABLE carrito (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  carrito_id BIGINT AUTO_INCREMENT NOT NULL,
  product_id BIGINT AUTO_INCREMENT NOT NULL


);

DROP TABLE IF EXISTS confirm;

CREATE TABLE confirm (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  carrito_id BIGINT AUTO_INCREMENT NOT NULL,
  clientes_id BIGINT AUTO_INCREMENT NOT NULL


);